// script.js

// Sample product data (you can replace this with dynamic data)
const products = [
    { id: 1, title: "Hp Laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$19.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/78.jpg" },
    { id: 2, title: "Dell Laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecatiutfkyfglutgymftftfgtglf", price: "$29.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/77-400x400.jpg" },
    { id: 3, title: "Lenovo laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecation.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/04-400x400.jpg" }
    ,{ id: 4, title: "Sony laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/73-400x400.jpg" },{ id: 5, title: "Asus laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/02-400x400.jpg" },{ id: 6, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/76-400x400.jpg" },    { id: 7, title: "Hp Laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$19.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/03-400x400.jpg" },
    { id: 8, title: "Dell Laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$29.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/01-400x400.jpg" },
    { id: 9, title: "Lenovo laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecation.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/11.jpg" }
    ,{ id: 10, title: "Sony laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/75-400x400.jpg" },{ id: 11, title: "Asus laptop", description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio tempora vitae iusto aliqui dolores perspiciatis commodi delectus minus sed obcaecati", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/79.jpg" },{ id: 12, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/78.jpg" }
    ,{ id: 13, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/16-800x800.jpg" },{ id: 14, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/120-800x800.jpg" }
    ,{ id: 15, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/17-800x800.jpg"}
    ,{ id: 16, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/21-800x800.jpg" }
    ,{ id: 17, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/112-800x800.jpg" }
    ,{ id: 18, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://demothemesky-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/111-800x800.jpg" }
    ,{ id: 19, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/78.jpg" }
    ,{ id: 20, title: "Aser Laptop", description: "This is the description for Product 3.", price: "$39.99", image: "https://ecomall-be87.kxcdn.com/ecomall/wp-content/uploads/2023/03/78.jpg" }
  ];
  
  function saveToLocalStorage(productId) {
    const product = products.find(item => item.id === productId);
    localStorage.setItem("selectedProduct", JSON.stringify(product));
    window.location.href = "product-detail.html"; // Redirect to the detail page
  }
  